<?php

use App\Models\FinancialPo;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // License & Contract records are no longer mirrored into Financial
        // Management (the license sync was removed). Drop the POs that were
        // previously generated from licenses; their receipts cascade away with them
        // via the financial_receipts foreign key.
        //
        // DB::table (not the Eloquent model) so this also removes any dismissed
        // (soft-deleted) license POs, which the soft-delete scope would hide.
        DB::table('financial_pos')
            ->where('source', FinancialPo::SOURCE_LICENSE)
            ->delete();

        // The license_contract_id column is intentionally kept so this change is
        // reversible without a schema migration.
    }

    public function down(): void
    {
        // No-op: deleted license POs and their receipts cannot be restored. They
        // can be regenerated by reinstating a license sync.
    }
};
