<?php

use App\Models\FinancialPo;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // Subscriptions are no longer mirrored into Financial Management (the sync
        // was removed and POs are now entered by hand). Drop the POs that were
        // previously generated from subscription renewals and pay-as-you-go usage;
        // their receipts cascade away via the financial_receipts foreign key.
        //
        // DB::table (not the Eloquent model) so this also removes any dismissed
        // (soft-deleted) subscription POs, which the soft-delete scope would hide.
        DB::table('financial_pos')
            ->whereIn('source', [
                FinancialPo::SOURCE_SUBSCRIPTION,
                FinancialPo::SOURCE_SUBSCRIPTION_PAYG,
            ])
            ->delete();

        // The subscription_id / subscription_renewal_id columns are intentionally
        // kept so this change is reversible without a schema migration.
    }

    public function down(): void
    {
        // No-op: deleted subscription POs and their receipts cannot be restored.
        // They can be regenerated by reinstating the subscription sync.
    }
};
